# Aquí orquestamos el caos. Cada servicio es un pequeño mundo de alegría y desesperación.
services:
  db:
    # La base de datos, el cerebro de la operación. Si se cae, nos caemos todos.
    image: postgres:15-alpine
    container_name: asir_db
    restart: always
    environment:
      POSTGRES_USER: admin_fichaje
      POSTGRES_PASSWORD: password_muy_segura
      POSTGRES_DB: gestion_fichajes
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - asir_network

  backend:
    # El backend, la lógica oscura que nadie entiende pero que, milagrosamente, funciona.
    build: ./backend
    container_name: asir_backend
    restart: always
    volumes:
      - ./backend:/app
      - ./pure-ftpd.pem:/app/pure-ftpd.pem:ro
    ports:
      - "8000:8000"
    environment:
      # Usamos el nombre del servicio 'db' para la conexión
      DATABASE_URL: postgresql://admin_fichaje:password_muy_segura@db:5432/gestion_fichajes
    depends_on:
      - db
      - ftps_server
    networks:
      - asir_network

  frontend:
    # El frontend, la cara bonita. Lo que el usuario ve y con lo que interactúa. Pobre de él.
    build: ./frontend
    container_name: asir_frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - asir_network

  ftps_server:
    # Un servidor FTP en pleno siglo XXI. Porque somos unos románticos y nos gusta lo retro.
    image: stilliard/pure-ftpd
    container_name: asir_ftps
    restart: always
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: asir_ftps
      FTP_USER_NAME: amado
      FTP_USER_PASS: jerez2026
      FTP_USER_HOME: /home/amado
      ADDED_FLAGS: "--tls=1" 
    volumes:
      - ./ftp_data:/home/amado
      - ./pure-ftpd.pem:/etc/ssl/private/pure-ftpd.pem:ro
    networks:
      - asir_network

  adminer:
    # Adminer, para cotillear la base de datos directamente. Porque a veces no nos fiamos de nuestra propia API.
    image: adminer
    container_name: asir_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - asir_network

networks:
  # La red que une a todos nuestros servicios. Como una gran familia disfuncional.
  asir_network:
    driver: bridge